USE hospital_analytics;

-- Q1 Which dept have highest patient volume
SELECT
d.dept_Name,
COUNT(distinct a.patient_Id) AS patient_volume
FROM patients AS p
JOIN appointment AS a
ON p.patient_Id=a.patient_Id
JOIN doctor AS doc
ON doc.doct_Id=a.doct_Id
JOIN department AS d
ON d.dept_Id=doc.dept_Id
GROUP BY dept_Name
ORDER BY patient_volume DESC;

-- Q2 Which ward has highest number of bed admissions
SELECT
w.ward_Name,
COUNT(*) AS occupancy
FROM ward AS w
JOIN bed AS b
ON b.ward_No=w.ward_No
JOIN bedrecords AS br
ON br.bed_No=b.bed_No
GROUP BY ward_Name
ORDER BY occupancy DESC;

-- Q3 What is average number of admissons per bed in each ward?
SELECT
    w.ward_Name,
    COUNT(DISTINCT b.bed_No) AS total_beds,
    COUNT(br.admission_Id) AS total_admissions,
    ROUND(
        COUNT(br.admission_Id) / COUNT(DISTINCT b.bed_No),
        4
    ) AS admissions_per_bed
FROM ward AS w
JOIN bed AS b
    ON b.ward_No = w.ward_No
LEFT JOIN bedrecords AS br
    ON br.bed_No = b.bed_No
GROUP BY w.ward_No, w.ward_Name
ORDER BY admissions_per_bed DESC;

-- Q4 No. of beds in each ward
SELECT
w.ward_Name,
COUNT(*) AS tot_beds
FROM ward AS w
JOIN bed AS b
ON b.ward_No=w.ward_No
GROUP BY w.ward_Name
ORDER BY tot_beds DESC;

-- Q5 Average length of stay
SELECT 
AVG(DATEDIFF(discharge_Date,admission_Date)) AS avg_stay
FROM bedrecords;

-- Q6 Which ward have longest avg patient stay?
SELECT 
ward_Name,
AVG(DATEDIFF(discharge_Date,admission_Date)) AS avg_stay
FROM bedrecords 
JOIN bed
ON bedrecords.bed_No=bed.bed_No
JOIN ward 
ON ward.ward_No=bed.ward_No
GROUP BY ward_Name;

-- Q7 What is total revenue generated by each mode of payment?
SELECT
mode_of_payment,
SUM(amount) as tot_revenue
FROM bedrecords
GROUP BY mode_of_payment
ORDER BY tot_revenue DESC;